on: [push, pull_request]

name: CI

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: toolchain-test2-${{ hashFiles('rust-toolchain') }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: deps-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            target/.rustc_info.json
            target/debug
          key: target-debug-${{ github.run_number }}
          restore-keys: |
            target-debug-

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
